#ifndef PCH_H
#define PCH_H
#if defined __cplusplus
#include <set>
#include <memory>

#include <QDragMoveEvent>
#include <QMimeData>
#include <QDrag>
#include <QFileInfo>
#include <QPainter>
#include <QRect>
#include <QFileDialog>
#include <QStandardPaths>
#include <QMessageBox>
#include <QDesktopServices>
#include <QProgressDialog>
#include <QDialog>
#include <QUrlQuery>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <QNetworkRequest>
#include <QByteArray>
#include <QTextBlock>
#include <QPixmap>
#include <QMenu>
#include <QSpinBox>
#include <QDialogButtonBox>
#include <QLocale>
#include <QDir>
#include <QTableView>
#include <QScrollBar>
#include <QFileInfoList>
#include <QStyle>
#include <QDesktopWidget>
#include <QMainWindow>
#include <QTextEdit>
#include <QNetworkAccessManager>
#include <QNetworkReply>
#include <QProcess>
#include <QMap>
#include <QThread>
#include <QComboBox>
#include <QListWidgetItem>
#include <QSystemTrayIcon>
#include <QPaintEvent>
#include <QFontMetrics>
#include <QStylePainter>
#include <QStyleOptionButton>
#include <QPushButton>
#include <QKeyEvent>
#include <QTimer>
#include <QItemDelegate>
#include <QStringList>
#include <QAbstractTableModel>
#include <QApplication>
#include <QListWidget>
#include <QCheckBox>
#include <QHeaderView>
#include <QRegularExpression>
#include <QTemporaryDir>
#include <QTemporaryFile>
#include <QTextCodec>
#include <QHttpMultiPart>
#include <QClipboard>
#include <QFrame>
#include <QSize>
#include <QUrl>
#include <QObject>
#include <QEventLoop>
#include <QFile>
#include <QAbstractButton>
#include <QCloseEvent>
#include <QStyledItemDelegate>
#include <QSqlDatabase>
#include <QSqlQuery>
#include <QVariant>
#include <QSettings>
#include <QtGlobal>
#include <QHash>
#include <QSharedMemory>
#endif
#endif // PCH_H
